### ISSUE TITLE
Too small "main" partition prevents resizing during flashing

### ISSUE THREAD

**Issue by SepticFuddy** [ADeadTrousers/android_device_Unihertz_Atom_LXL#9]
When trying to install after disabling AVB and doing a full wipe, I get this error:
![install error](https://user-images.githubusercontent.com/73045807/115046564-d58bf600-9e94-11eb-8630-104f1c44637b.jpeg)

**Comment by ADeadTrousers** [comment]
Just updated some docs and added more vendor information to BoardConfigCommon.mk.
2208c65aff04d3fefd03b6bdc927da2abe6cefad

**Comment by ADeadTrousers** [comment]
Next I will create some precompiled super.img for every device.

**Comment by ADeadTrousers** [comment]
super.img-files are now part of the releases which corresponds the latest stock rom release.
They need to be updated only when a new stock gets released:
https://github.com/ADeadTrousers/android_device_Unihertz_Atom_L_EEA/releases/download/20210226-alpha/super.img-eea.7z
https://github.com/ADeadTrousers/android_device_Unihertz_Atom_XL_EEA/releases/download/20201219-alpha/super.img-seea.7z
https://github.com/ADeadTrousers/android_device_Unihertz_Atom_L_TEE/releases/download/20210415-alpha/super.img-tee.7z
https://github.com/ADeadTrousers/android_device_Unihertz_Atom_XL_TEE/releases/download/20210415-alpha/super.img-stee.7z
I also added a "troubleshooting"-section to the install guide for this.
03ecd82576d1f752af9ec26a8645b20fff885e9a

**Comment by SepticFuddy** [comment]
STEE super.img confirmed working
